apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oy6o2f1ll-java-springboot
  janus-idp.io/tekton: oy6o2f1ll-java-springboot
  backstage.io/kubernetes-id: oy6o2f1ll-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oy6o2f1ll-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
